type: object
required:
  - cpartySessionId
  - citizenSessionId
  - ircCode
properties:
  cpartySessionId:
    type: string
    description: Session ID received from user authentication or two-factor authentication service
  citizenSessionId:
    type: string
    description: Citizen session ID received from citizen session creation service
  ircCode:
    type: string
    description: IRC code of the product 